GenericExecuteSynth "echo -n '$DATA' | /home/user_name/piper-spd-wrapper.sh $RATE" #user_name должно сооствествать имени пользователя
GenericLanguage "ru" "ru_RU" "UTF-8"
AddVoice "ru" "MALE1" "denis"
DefaultVoice "denis"

# Опционально (чтобы $RATE был именно от -100 до +100)
GenericRateMultiply 1
GenericRateAdd 0
